### PR TITLE
fix(dao) validate timestamps, allow only positive numbers. Fixes #1542

### LINKED ISSUE #1542: Inconsistent `created_at` Timestamp Formats
### Summary

When attempting to `PUT` against an existing API definition via the management API, the timestamp format for the `created_at` field is not consistent with the one required for `POST`.

This likely affects other endpoints as well (Plugins, ACLs, etc).
### Steps To Reproduce

Please see https://github.com/plukevdh/kong-fail for a self-contained instance with steps to reproduce issue seen.
### Additional Details & Logs
- Kong version (`0.8.3`)
- Kong configuration (included in the issue repo above)
- Kong error logs mostly concerned with `2016/08/24 17:20:17 [error] 101#0: *35 [lua] responses.lua:99: handler(): ERROR: column "created_at" is of type timestamp without time zone but expression is of type integer (215), client: 192.168.99.1, server: , request: "POST /apis HTTP/1.1",` (also see live logs from issue repo)
- Operating System: Docker/Linux

### PR DESCRIPTION
**Pull request by Tieske**
### Summary

* validates timestamps to be numbers > 0

### Issues resolved

Fix #1542

### CODE REVIEW

File: spec/01-unit/07-schema_validation_spec.lua [hunk 1]
```diff
@@ -230,6 +245,31 @@ describe("Schemas", function()
         assert.same("boolean", type(values.boolean_val))
       end)
 
+      it("should not return an error when a `timestamp` is passed as a string", function()
+        local values = {string = "test", timestamp = "123"}
+
+        local valid, err = validate_entity(values, schema)
+        assert.falsy(err)
+        assert.truthy(valid)
+        assert.same("number", type(values.timestamp))
```
Comment (thibaultcha) [inline spec/01-unit/07-schema_validation_spec.lua]: should be `assert.equal()`

File: spec/01-unit/07-schema_validation_spec.lua [hunk 2]
```diff
@@ -230,6 +245,31 @@ describe("Schemas", function()
...
+        assert.falsy(valid)
+        assert.are.same("timestamp is not a timestamp", err.timestamp)
+      end)
+
+      it("should return an error when a `timestamp` is a negative number", function()
+        local values = {string = "test", timestamp = "-123"}
+
+        local valid, err = validate_entity(values, schema)
+        assert.falsy(valid)
+        assert.are.same("timestamp is not a timestamp", err.timestamp)
```
Comment (thibaultcha) [inline spec/01-unit/07-schema_validation_spec.lua]: ditto (no `are` too)

File: spec/01-unit/07-schema_validation_spec.lua [hunk 3]
```diff
@@ -230,6 +245,31 @@ describe("Schemas", function()
...
+        assert.truthy(valid)
+        assert.same("number", type(values.timestamp))
+      end)
+
+      it("should return an error when a `timestamp` is not a number", function()
+        local values = {string = "test", timestamp = "just a string"}
+
+        local valid, err = validate_entity(values, schema)
+        assert.falsy(valid)
+        assert.are.same("timestamp is not a timestamp", err.timestamp)
```
Comment (thibaultcha) [inline spec/01-unit/07-schema_validation_spec.lua]: ditto
