### PR TITLE
fix(router) preserve_host always fetches the request's Host

### LINKED ISSUE #2824: Open API3.0 Spec
NOTE: GitHub issues are reserved for bug reports only.

Please read the CONTRIBUTING.md guidelines to learn on which channels you can
seek for help and ask general questions:

https://github.com/Mashape/kong/blob/master/CONTRIBUTING.md#where-to-seek-for-help

### Summary

SUMMARY_GOES_HERE

### Steps To Reproduce

1.
2.
3.
4.

### Additional Details & Logs

- Kong version (`$ kong version`)
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (registered APIs/Plugins & configuration file)
- Operating System

### PR DESCRIPTION
**Pull request by thibaultcha**
Summary
-------

It was reported in #2825 that `preserve_host` seemed to behave wrongly
upon subsequent call of a same API if that API had no `hosts`.

Since matches APIs are cached, and so are their `upstream_host` values,
I investigated around the LRU cache of our matches in the router. What I
discovered is, considering the following API:

    {
        "name": "example",
        "upstream_url": "http://httpbin.org",
        "uris": ["/example"]
    }

The router would try to save cycles by *not* reading the
`ngx.var.http_host` variable, since no API is configured to match on a
Host header.

However, the Host is also part of the cache key since the introduction
of the LRU cache in the router. But in the above case, considering the
following two requests:

    GET /example HTTP/1.1
    Host: domain1.com

    GET /example HTTP/1.1
    Host: domain2.com

Both matches would be cached under the **same** key (since the
`req_host` argument of `find_api` is `nil` because the router does not
read the Host header):

    GET:/example:

Notice the lack of Host part after the last colon.

Hence, once this API would be matched after the first request, its
cached `upstream_host` would be `domain1.com`, and subsequent calls with
`Host: domain2.com` would hit the same key, and yield the same
`upstream_host` as the first request.

The approach taken by this fix is to **always** retrieve the Host
header. This choice is driven by the fact that cache keys should have as
high a cardinality as possible, and to ensure we avoid such duplicate
keys in the future.

Changes
-------

* remove `grab_header` optimization from `router.lua`
* remove `grab_header` tests from unit test suite
* make `find_api()`'s 3rd argument (Host header) mandatory
* update related unit tests to reflect the above change
* new regression test for this issue

---

Fix #2824

### CODE REVIEW

File: spec/01-unit/010-router_spec.lua [hunk 1]
```diff
@@ -1344,7 +1304,7 @@ describe("Router", function()
 
         local router = assert(Router.new(use_case))
 
-        local _ngx = mock_ngx("GET", "/users/123/profile/hello/world", {})
+        local _ngx = mock_ngx("GET", "/users/123/profile/hello/world", { ["host"] = "domain.org" })
```
Comment (hishamhm) [inline spec/01-unit/010-router_spec.lua]: Friendly nudge to point out you're breaking the 80-char limit all over the place. ;)

(And that is to say that I'd rather see the rule relaxed for sensible cases like this than the to have the PR changed for this trivial reason.)

Comment (thibaultcha) [inline spec/01-unit/010-router_spec.lua]: Yeah... I tend to not follow the 80 chars rule (enough) in tests file. But you are right! And I do think this warrants a little cleanup! It's a quick job :)

Comment (thibaultcha) [inline spec/01-unit/010-router_spec.lua]: done :) At least for the tests impacted by this changeset!

File: spec/01-unit/010-router_spec.lua [hunk 2]
```diff
@@ -95,14 +95,14 @@ describe("Router", function()
 
     it("[uri]", function()
       -- uri
-      local match_t = router.select("GET", "/my-api")
+      local match_t = router.select("GET", "/my-api", "domain.org")
```
Comment (p0pr0ck5) [inline spec/01-unit/010-router_spec.lua]: traditionally (and per IANA recommendations) we should probably use "example.com" or "example.org". it's not a _huge_ difference, but historically usage of things like "domain.com" has been problematic (that domain was used to serve malware at one point).

Comment (thibaultcha) [inline spec/01-unit/010-router_spec.lua]: dully noted - my intent is to replace those with `example.org` in a later contribution, as many tests (outside of the scope of this PR) already use `domain.com` :( (I put them there in the first place 😅)

**Comment by thibaultcha** [comment]
Thanks @hishamhm @p0pr0ck5 !
