### PR TITLE
fix(oauth2) dont try to hide credentials in a multipart req body

### LINKED ISSUE #1952: [oauth2] Error when POST a file with multipart/form-data
### Summary

Hello, I have a little problem with kong, when I try to send a request with the content-type multipart/form-data (oauth2 plugins for the authentication), I received that error in the log and it's impossible to perform the request, my version is 0.9.5, what can I do please?
pasted image at 2017_01_09 03_01 pm

### Steps To Reproduce

1. Configure an oauth2 plugin
2. Add an Api behind
3. Upload a file with the content-type `multipart/form-data`

### Additional Details & Logs
pasted image at 2017_01_09 02_49 pm 1
pasted image at 2017_01_09 02_49 pm

- Kong version (0.9.5)
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (registered APIs/Plugins & configuration file)
- Operating System

### PR DESCRIPTION
**Pull request by p0pr0ck5**
### Summary

Don't try to remove credentials from request bodies when the request is a multipart upload. This prevents a thread abort when trying to index a non-existent table.

### Full changelog

* fix(oauth2) dont try to hide credentials in a multipart req body

### Issues resolved

Fix #1952

### CODE REVIEW

**Comment by p0pr0ck5** [comment]
Failed test seems unrelated to this change.

File: kong/plugins/oauth2/access.lua [hunk 1]
```diff
@@ -422,7 +422,11 @@ local function parse_access_token(conf)
       parameters[ACCESS_TOKEN] = nil
       ngx.req.set_uri_args(parameters)
 
-      if ngx.req.get_method() ~= "GET" then -- Remove from body
+      local content_type = req_get_headers()[CONTENT_TYPE]
+      local is_upload = content_type and
+        string_find(content_type:lower(), "multipart/form-data", 1, true)
```
Comment (Tieske) [inline kong/plugins/oauth2/access.lua]: no need for `lower()` here

> Since the 0.6.9 release, all the header names in the Lua table returned are converted to the pure lower-case form by default, unless the raw argument is set to true (default to false).

**Comment by p0pr0ck5** [comment]
@Tieske able to take another look at this one? rebased on top of `next` to fix a merge conflict

**Comment by thibaultcha** [comment]
To be more protective, shouldn't `get_post_args()` only be called when the MIME type is `application/x-www-form-urlencoded`?
