### PR TITLE
fix(api schema) better check for request_host

### LINKED ISSUE #856: invalid request_host not verified
```
$ http :8001/apis name=test upstream_url=http://httpbin.com request_host=/httpbin
HTTP/1.1 201 Created
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Type: application/json; charset=utf-8
Date: Sat, 09 Jan 2016 04:03:06 GMT
Server: kong/0.5.4
Transfer-Encoding: chunked

{
    "created_at": 1452312186000,
    "id": "5e03d3f4-63d6-475c-a09f-a7b056676d8e",
    "name": "test",
    "request_host": "/httpbin",
    "upstream_url": "http://httpbin.com"
}
```

Accidentally inserted a URI in place of a host in `requets_host` without any error.

### PR DESCRIPTION
**Pull request by thibaultCha**
The old check would allow a value of `/hello` as a `request_host`.

This change uses a Lua pattern to validate a `request_host` and does so
in the `check_request_host` function, removing the need for the `regex`
field in schema (not used anywhere else). However, the `regex` schema field
capability is not removed by this change.

This also slightly improves the checks made on `request_host` and
`request_path` and adds many test cases for `rquest_host` validation.

Fix #856

### CODE REVIEW

File: spec/unit/dao/entities_schemas_spec.lua [hunk 1]
```diff
@@ -84,15 +84,50 @@ describe("Entities Schemas", function()
...
+        assert.equal("Invalid value: "..v, (errors and errors.request_host or ""))
+        assert.falsy(errors.request_path)
+        assert.False(valid)
+      end
+    end)
+
+    it("should accept valid request_host", function()
+      local valids = {"hello.com", "hello.fr", "test.hello.com", "1991.io", "hello.COM",
+                      "HELLO.com", "123helloWORLD.com", "mockbin.123", "mockbin-api.com",
+                      "hello.abcd", "mockbin_api.com"}
```
Comment (thibaultCha) [inline spec/unit/dao/entities_schemas_spec.lua]: @Tieske @thefosk Could you please review the valid and invalid cases pointed out by those tests?

Comment (Tieske) [inline spec/unit/dao/entities_schemas_spec.lua]: the invalid ones should include elements starting or ending with `-`. The underscore is in the allowed section, but is not really allowed, then again, some DNS services use it to add some special meaning to elements, so we probably should allow for that.

Comment (thibaultCha) [inline spec/unit/dao/entities_schemas_spec.lua]: Updated the patch with this check and more test cases.
