### PR TITLE
fix(hmac-auth) generate a credential secret if none provided

### LINKED ISSUE #2143: Error calling HMAC plugin create_hash
### Summary

I have recently configured HMAC auth via the bundled plugin with only default settings on a new API. The only other plugin running on this API is the CORS bundled plugin. Upon receiving the signed request, kong returns a 500 error, with the logs:

```sh
2017-02-28T17:55:11.285701+00:00 heroku[router]: at=info method=POST path="/mockbin/post" host=api.<ourcompany>.com request_id=b78ce346-fd44-4252-a845-b1288eff5123 fwd="96.65.75.149,162.158.74.140" dyno=web.1 connect=1ms service=115ms status=500 bytes=255
2017-02-28T17:55:11.277516+00:00 app[web.1]: 2017/02/28 17:55:11 [error] 96#0: *4061 lua entry thread aborted: runtime error: .../.heroku/share/lua/5.1/kong/plugins/hmac-auth/access.lua:99: bad argument #1 to 'create_hash' (string expected, got nil)
2017-02-28T17:55:11.277528+00:00 app[web.1]: stack traceback:
2017-02-28T17:55:11.277529+00:00 app[web.1]: coroutine 0:
2017-02-28T17:55:11.277529+00:00 app[web.1]: 	[C]: in function 'create_hash'
2017-02-28T17:55:11.277530+00:00 app[web.1]: 	.../.heroku/share/lua/5.1/kong/plugins/hmac-auth/access.lua:99: in function 'validate_signature'
2017-02-28T17:55:11.277531+00:00 app[web.1]: 	.../.heroku/share/lua/5.1/kong/plugins/hmac-auth/access.lua:168: in function 'execute'
2017-02-28T17:55:11.277532+00:00 app[web.1]: 	....heroku/share/lua/5.1/kong/plugins/hmac-auth/handler.lua:14: in function 'access'
2017-02-28T17:55:11.277534+00:00 app[web.1]: 	/app/.heroku/share/lua/5.1/kong.lua:193: in function 'access'
2017-02-28T17:55:11.277535+00:00 app[web.1]: 	access_by_lua(nginx.conf:87):2: in function <access_by_lua(nginx.conf:87):1>, client: 96.65.75.149, server: _, request: "POST /mockbin/post HTTP/1.1", host: "api.<ourcompany>.com", referrer: "http://localhost:3000/"
```

I don't see what the `nil` value stems from. By line `168` (https://github.com/Mashape/kong/blame/0.7.0/kong/plugins/hmac-auth/access.lua#L168) the `hmac_params` have been collected and validated, `headers` are present, and `ngx.req` is present. What's the issue?

### Steps To Reproduce

```sh
curl https://api.<ourcompany>.com/mockbin/post --data 'foobar' -X POST --header 'content-md5: 3858f62230ac3c915f300c664312c63f' --header 'content-type: text/plain' --header 'date: Tue, 28 Feb 2017 19:42:34 GMT' --header 'authorization: hmac username="customercontact-381", algorithm="hmac-sha1", headers="date content-md5", signature="MTRjMTVkYzI4ODUwNjllMjRlMDhkY2ViNmQ4NWQxODVmYzFjMDA5MQ=="' -i
```

### Additional Details & Logs

Here is the line in question: https://github.com/Mashape/kong/blame/0.7.0/kong/plugins/hmac-auth/access.lua#L58
The API in question is configured at the `mockbin` path.
- Kong version `0.7.0`
- Operating System `heroku`
- Installed via: https://github.com/heroku/heroku-kong

### PR DESCRIPTION
**Pull request by p0pr0ck5**
### Summary

Since the credential secret is required to compute the signature, create a random secret which will be  displayed back to the user as part of the response body.

### Full changelog

* generate a credential secret if none provided

### Issues resolved

Fix #2143

### CODE REVIEW

File: kong/plugins/hmac-auth/daos.lua [hunk 1]
```diff
@@ -1,3 +1,9 @@
+local utils = require "kong.tools.utils"
+
+local function random_secret(t)
+  return utils.random_string()
+end
```
Comment (Tieske) [inline kong/plugins/hmac-auth/daos.lua]: why wrapping a single function call into another function?

if it is to drop the argument, then maybe a small comment would make that clear

File: spec/03-plugins/09-hmac-auth/02-api_spec.lua [hunk 2]
```diff
@@ -39,6 +39,20 @@ describe("Plugin: hmac-auth (API)", function()
...
+          path = "/consumers/bob/hmac-auth/",
+          body = {
+            username = "bob",
+          },
+          headers = {["Content-Type"] = "application/json"}
+        })
+
+        local body = assert.res_status(201, res)
+        credential = cjson.decode(body)
+        assert.is.not_nil(credential.secret)
```
Comment (Tieske) [inline spec/03-plugins/09-hmac-auth/02-api_spec.lua]: fyi; you could write this as:
```lua
assert.response(res).has.status(201)
local json = assert.response(res).has.jsonbody()
assert.is.not_nil(json.secret)
```
these custom assertions (in `spec/helpers.lua`) generally provide better error messages when they fail.

**Comment by Tieske** [comment]
@poprocks ^^ approved it, but assuming there will be another pr with the migrations

File: spec/03-plugins/09-hmac-auth/02-api_spec.lua (hunk 2 above)
Comment (p0pr0ck5) [inline spec/03-plugins/09-hmac-auth/02-api_spec.lua]: Thanks, this was a copypasta from the test above. Nice to know though!

File: kong/plugins/hmac-auth/daos.lua (hunk 1 above)
Comment (p0pr0ck5) [inline kong/plugins/hmac-auth/daos.lua]: yeah, silly mistake, we can just set `default = utils.random_string()`. ill fix that

**Comment by p0pr0ck5** [comment]
@Tieske re-up'd with an adjustment to the dao. I'd be happy to work on the migration part of it, but I could use some hand holding there.

**Comment by Tieske** [comment]
@p0pr0ck5 checkout the 2 migration files for the Kong core in the dao. They provide quite some examples.

Ping me if you need more.

**Comment by thibaultcha** [comment]
@p0pr0ck5 Are you planning on providing the migration in this PR or another one?

**Comment by p0pr0ck5** [comment]
Will handle the migration in another PR, since it's fairly destructive (after talking to tieske it seems the best plan for that is to simply delete all entries with a null `secret`), so id like to test it a bit, and not block this PR.
