### PR TITLE
hotfix(conf) convert custom nginx conf dns_resolver to string

### LINKED ISSUE #2319: Kong 0.10.0 startup eror
### Summary

just upgraded my kong from 0.9.7 to 0.10.0 and seeing below crash at the startup,

```
/usr/local/share/lua/5.1/kong/cmd/start.lua:34: /usr/local/share/lua/5.1/kong/cmd/utils/prefix_handler.lua:285: invalid replacement value (a table)
stack traceback:
	[C]: in function 'error'
	/usr/local/share/lua/5.1/kong/cmd/start.lua:34: in function 'cmd_exec'
	/usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:88>
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:45>
	/usr/local/bin/kong:5: in function 'file_gen'
	init_worker_by_lua:42: in function <init_worker_by_lua:40>
	[C]: in function 'pcall'
	init_worker_by_lua:49: in function <init_worker_by_lua:47>


```

### Additional Details & Logs

- Kong version 0.10.0
- kong logs 
```
cassandra.test.svc.cluster.local [10.100.0.129] 9042 (?) open
starting background script
Starting kong
Setting up watches.
Watches established.
Error:

2017/04/01 13:44:44 [verbose] Kong: 0.10.0
2017/04/01 13:44:44 [debug] ngx_lua: 10007
2017/04/01 13:44:44 [debug] nginx: 1011002
2017/04/01 13:44:44 [debug] Lua: LuaJIT 2.1.0-beta2
2017/04/01 13:44:44 [verbose] reading config file at /etc/kong/kong.conf
2017/04/01 13:44:44 [debug] admin_listen = "0.0.0.0:8001"
2017/04/01 13:44:44 [debug] admin_listen_ssl = "0.0.0.0:8444"
2017/04/01 13:44:44 [debug] admin_ssl = true
2017/04/01 13:44:44 [debug] anonymous_reports = false
2017/04/01 13:44:44 [debug] cassandra_consistency = "ONE"
2017/04/01 13:44:44 [debug] cassandra_contact_points = {"cassandra.test.svc.cluster.local"}
2017/04/01 13:44:44 [debug] cassandra_data_centers = {"dc1:2","dc2:3"}
2017/04/01 13:44:44 [debug] cassandra_keyspace = "kong"
2017/04/01 13:44:44 [debug] cassandra_lb_policy = "RoundRobin"
2017/04/01 13:44:44 [debug] cassandra_password = "******"
2017/04/01 13:44:44 [debug] cassandra_port = 9042
2017/04/01 13:44:44 [debug] cassandra_repl_factor = 1
2017/04/01 13:44:44 [debug] cassandra_repl_strategy = "SimpleStrategy"
2017/04/01 13:44:44 [debug] cassandra_ssl = false
2017/04/01 13:44:44 [debug] cassandra_ssl_verify = false
2017/04/01 13:44:44 [debug] cassandra_timeout = 5000
2017/04/01 13:44:44 [debug] cassandra_username = "cassandra"
2017/04/01 13:44:44 [debug] cluster_listen = "0.0.0.0:7946"
2017/04/01 13:44:44 [debug] cluster_listen_rpc = "127.0.0.1:7373"
2017/04/01 13:44:44 [debug] cluster_profile = "wan"
2017/04/01 13:44:44 [debug] cluster_ttl_on_failure = 3600
2017/04/01 13:44:44 [debug] custom_plugins = {}
/usr/local/share/lua/5.1/kong/cmd/start.lua:34: /usr/local/share/lua/5.1/kong/cmd/utils/prefix_handler.lua:285: invalid replacement value (a table)
stack traceback:
	[C]: in function 'error'
	/usr/local/share/lua/5.1/kong/cmd/start.lua:34: in function 'cmd_exec'
	/usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:88>
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:45>
	/usr/local/bin/kong:5: in function 'file_gen'
	init_worker_by_lua:42: in function <init_worker_by_lua:40>
	[C]: in function 'pcall'
	init_worker_by_lua:49: in function <init_worker_by_lua:47>
2017/04/01 13:44:44 [debug] database = "cassandra"
2017/04/01 13:44:44 [debug] dns_hostsfile = "/etc/hosts"
2017/04/01 13:44:44 [debug] dns_resolver = {"10.100.0.10"}
2017/04/01 13:44:44 [debug] log_level = "notice"
2017/04/01 13:44:44 [debug] lua_code_cache = "on"
2017/04/01 13:44:44 [debug] lua_package_cpath = ""
2017/04/01 13:44:44 [debug] lua_package_path = "?/init.lua;./kong/?.lua"
2017/04/01 13:44:44 [debug] lua_socket_pool_size = 30
2017/04/01 13:44:44 [debug] lua_ssl_verify_depth = 1
2017/04/01 13:44:44 [debug] mem_cache_size = "128m"
2017/04/01 13:44:44 [debug] nginx_daemon = "on"
2017/04/01 13:44:44 [debug] nginx_optimizations = true
2017/04/01 13:44:44 [debug] nginx_worker_processes = "auto"
2017/04/01 13:44:44 [debug] pg_database = "kong"
2017/04/01 13:44:44 [debug] pg_host = "127.0.0.1"
2017/04/01 13:44:44 [debug] pg_port = 5432
2017/04/01 13:44:44 [debug] pg_ssl = false
2017/04/01 13:44:44 [debug] pg_ssl_verify = false
2017/04/01 13:44:44 [debug] pg_user = "kong"
2017/04/01 13:44:44 [debug] prefix = "/etc/kong/"
2017/04/01 13:44:44 [debug] proxy_listen = "0.0.0.0:80"
2017/04/01 13:44:44 [debug] proxy_listen_ssl = "0.0.0.0:443"
2017/04/01 13:44:44 [debug] serf_path = "serf"
2017/04/01 13:44:44 [debug] ssl = true
2017/04/01 13:44:44 [debug] ssl_cert = "/etc/secret-volume/ssh-publickey"
2017/04/01 13:44:44 [debug] ssl_cert_key = "/etc/secret-volume/ssh-privatekey"
2017/04/01 13:44:44 [debug] upstream_keepalive = 60
2017/04/01 13:44:44 [verbose] prefix in use: /etc/kong
2017/04/01 13:44:44 [verbose] preparing nginx prefix directory at /etc/kong
2017/04/01 13:44:44 [verbose] saving serf identifier to /etc/kong/serf/serf.id
2017/04/01 13:44:44 [debug] searching for OpenResty 'resty' executable
2017/04/01 13:44:44 [debug] /usr/local/openresty/bin/resty -V: 'nginx version: openresty/1.11.2.2'
2017/04/01 13:44:44 [debug] found OpenResty 'resty' executable at /usr/local/openresty/bin/resty
2017/04/01 13:44:44 [verbose] saving serf shell script handler to /etc/kong/serf/serf_event.sh
2017/04/01 13:44:44 [verbose] Admin SSL enabled, no custom certificate set: using default certificate
2017/04/01 13:44:44 [verbose] generating admin SSL certificate and key
2017/04/01 13:44:45 [verbose] could not start Kong, stopping services
2017/04/01 13:44:45 [verbose] leaving serf cluster
2017/04/01 13:44:45 [verbose] left serf cluster
2017/04/01 13:44:45 [verbose] stopping serf agent at /etc/kong/pids/serf.pid
2017/04/01 13:44:45 [debug] sending signal to pid at: /etc/kong/pids/serf.pid
2017/04/01 13:44:45 [debug] no pid file at: /etc/kong/pids/serf.pid
2017/04/01 13:44:45 [verbose] serf agent stopped
2017/04/01 13:44:45 [verbose] stopped services
```

### PR DESCRIPTION
**Pull request by bungle**
### Summary

If you have this in your custom nginx template:

```nginx
resolver ${{DNS_RESOLVER}} ipv6=off;
```

It will yield an error. This PR fixes the issue by transforming
the `dns_resolver` from `table` to `string` for template usage.

### Issues resolved

Fix #2319

### CODE REVIEW

File: spec/01-unit/03-prefix_handler_spec.lua [hunk 1]
```diff
@@ -154,6 +154,14 @@ describe("NGINX conf compiler", function()
...
       assert.matches("multi_accept on;", nginx_conf)
     end)
+    it("converts dns_resolver to string", function()
+      local nginx_conf = prefix_handler.compile_nginx_conf({
+        dns_resolver = { "8.8.8.8", "8.8.4.4" }
+      }, [[
+        "resolver ${{DNS_RESOLVER}} ipv6=off;"
+      ]])
+      assert.matches("resolver 8.8.8.8 8.8.4.4 ipv6=off;", nginx_conf, nil, true)
+    end)
```
Comment (p0pr0ck5) [inline spec/01-unit/03-prefix_handler_spec.lua]: Perhaps a regression test where dns_resolver is a string as well?

File: kong/cmd/utils/prefix_handler.lua [hunk 2]
```diff
@@ -180,6 +180,10 @@ local function compile_conf(kong_config, conf_template)
 
   compile_env = pl_tablex.merge(compile_env, kong_config, true) -- union
 
+  if type(compile_env.dns_resolver) == "table" then
```
Comment (thibaultcha) [inline kong/cmd/utils/prefix_handler.lua]: I think this value always is a table?

File: spec/01-unit/03-prefix_handler_spec.lua [hunk 3]
```diff
@@ -154,6 +154,14 @@ describe("NGINX conf compiler", function()
       assert.matches("worker_connections %d+;", nginx_conf)
       assert.matches("multi_accept on;", nginx_conf)
     end)
+    it("converts dns_resolver to string", function()
+      local nginx_conf = prefix_handler.compile_nginx_conf({
+        dns_resolver = { "8.8.8.8", "8.8.4.4" }
+      }, [[
+        "resolver ${{DNS_RESOLVER}} ipv6=off;"
```
Comment (thibaultcha) [inline spec/01-unit/03-prefix_handler_spec.lua]: :O This is a bit concerning. Apparently this is not in the template anymore, and maybe the user who reported it is using an old version of the template? We should check with him, and probably add it back... :/

File: spec/01-unit/03-prefix_handler_spec.lua (hunk 1 above)
Comment (bungle) [inline spec/01-unit/03-prefix_handler_spec.lua]: Do you mean something else than this:
https://github.com/Mashape/kong/blob/master/spec/01-unit/02-conf_loader_spec.lua#L240

File: spec/01-unit/03-prefix_handler_spec.lua (hunk 3 above)
Comment (bungle) [inline spec/01-unit/03-prefix_handler_spec.lua]: Yes, it is not. Is it problem to have that in case user wants to add a resolver line in his template? This will not break anything in case there is no resolver line in a template (our dns resolver uses this). We could also suggest user adding `for` loop in his template, but it would be a bit ugly.

Comment (bungle) [inline spec/01-unit/03-prefix_handler_spec.lua]: I mean that if user wants the Nginx resolver use the same resolvers as Kong DNS resolver and configure it in one place, does it hurt?

Comment (thibaultcha) [inline spec/01-unit/03-prefix_handler_spec.lua]: Hmmm at the same time, it is true we do not need it anymore since all of our DNS resolution is currently taken care of on the Lua-land... 

> I mean that if user wants the Nginx resolver use the same resolvers as Kong DNS resolve

I feel like this is a completely valid point, and to sum up the concerns, I would say they are: 

1. some users may indeed want to avoid duplicating their DNS nameservers in both the Kong config and a custom Nginx template, if they need to. 
2. at the same time, it feels like we do not need Nginx to create a resolver if Kong never uses it... seems wasteful
3. (on the long term) I am a bit concerned by the fact that we wrap each cosocket `:connect()` call with our own Lua-land resolver. While it is nice to be able to use the same DNS resolver everywhere and feed it with better features than the Nginx one, I am curious about the performance impact of that, and wonder if we should not instead invest time and energy in the Nginx resolver itself (a long-time thought of mine)
4. this change makes our current configuration types compatible with legacy Nginx templates, such as the one in use by the user who raised this issue

Because of 2. and 4. (probably most of the use-cases), I think it's fine to merge this patch as-is, without adding it back to the template are I suggested to maybe do. 

Do you agree with this reasoning?

File: kong/cmd/utils/prefix_handler.lua (hunk 2 above)
Comment (thibaultcha) [inline kong/cmd/utils/prefix_handler.lua]: I think we can merge this patch if we get rid of this if :)

File: spec/01-unit/03-prefix_handler_spec.lua (hunk 3 above)
Comment (bungle) [inline spec/01-unit/03-prefix_handler_spec.lua]: Absolutely, no need to add anything back to our templates. This is just to serve current custom template users (maybe just one).

File: spec/01-unit/03-prefix_handler_spec.lua (hunk 1 above)
Comment (thibaultcha) [inline spec/01-unit/03-prefix_handler_spec.lua]: > Perhaps a regression test where dns_resolver is a string as well?

Such a test exists [here](https://github.com/Mashape/kong/blob/master/spec/01-unit/02-conf_loader_spec.lua#L150-L156) for all array properties and not just `dns_resolver` :)

**Comment by thibaultcha** [comment]
Thanks!
