### PR TITLE
fix(plugins) use a sane wrapper around ngx.get_post_args

### LINKED ISSUE #1241: OAuth2 Plugin + "request body in temp file"
We're running into an issue with the oauth2 plugin on kong (v0.8.1) causing a 500 error when our request body is relatively large. We get an error like this:

```
2016/05/24 01:56:29 [error] 118#0: *2223 lua entry thread aborted: runtime error: /usr/local/share/lua/5.1/kong/plugins/oauth2/access.lua:106: requesty body in temp file not supported
stack traceback:
coroutine 0:
    [C]: in function 'get_post_args'
    /usr/local/share/lua/5.1/kong/plugins/oauth2/access.lua:106: in function 'retrieve_parameters'
    /usr/local/share/lua/5.1/kong/plugins/oauth2/access.lua:366: in function 'parse_access_token'
    /usr/local/share/lua/5.1/kong/plugins/oauth2/access.lua:419: in function 'execute'
    /usr/local/share/lua/5.1/kong/plugins/oauth2/handler.lua:12: in function 'access'
    /usr/local/share/lua/5.1/kong.lua:188: in function 'access'
    access_by_lua(nginx.conf:98):2: in function <access_by_lua(nginx.conf:98):1>
```

As a workaround, we found that we can set `client_body_buffer_size` in the nginx configuration so it doesn't write to a temporary file. Are there any other ways we can get this work rather than setting it to some arbitrary value and hope we don't ever get a request bigger than that?

It looks like its because it's trying to read the entire body to get oauth parameters. Perhaps it would be better to only do that if the request content type was one of the form data types?

### PR DESCRIPTION
**Pull request by p0pr0ck5**
### Summary

This call can fail in multiple ways, most notibly when the request body size is greater than client_body_buffer_size. Until a refactored plugin api is in place, we should catch errors (either Lua errors, or a returned error message from ngx).

### Full changelog

* fix(plugins) user a sane wrapper around ngx.get_post_args

### Issues resolved

Fix #1241

### CODE REVIEW

**Comment by p0pr0ck5** [comment]
Yeah, definitely reading the request body needs to be part of a core abstraction. :)

And yeah, duplicating these functions smells bad. Not sure what module to put this in? `kong/tools/utils`?

File: kong/plugins/aws-lambda/handler.lua [hunk 1]
```diff
@@ -23,6 +23,22 @@ function AWSLambdaHandler:new()
...
+local function get_req_body_args()
+  -- a few things can happen in this function.
+  -- it can throw an error, or it can return nil and a string
+  -- describing an error (such as when the size of the args
+  -- is greater client_body_buffer_size)
+  local ok, res, err = pcall(ngx_req_get_post_args)
+
+  if not ok or err then
+    local msg = res and res or err
+    ngx.log(ngx.ERR, msg)
```
Comment (thibaultcha) [inline kong/plugins/aws-lambda/handler.lua]: We should give some contexts to such errors in the message:
```
ngx.log(ngx.ERR, "could not get body args: ", err)
```

**Comment by p0pr0ck5** [comment]
@thibaultcha you have in mind something like this? https://gist.github.com/p0pr0ck5/f4c58b2f9bbbe29e2b27b17a6255d3c6

**Comment by p0pr0ck5** [comment]
Actually on second thought, I wonder if we need to design a new public API that abstracts not only functionality, but content. I don't think we should just provide wrapped functions to retrieve request/response data; I wonder if we should also have kong core retrieve that data and provide a cache/table mechanism to hold headers/cookies/uri/body/etc, so multiple plugins aren't needlessly hitting the same `ngx` API over and over again. This may need some more thought and discussion.

**Comment by thibaultcha** [comment]
Yes, this is already the idea behind it :)

However, this PR is not about implementing the Public Lua API :)

File: kong/plugins/aws-lambda/handler.lua [hunk 2]
```diff
@@ -7,14 +7,16 @@ local utils = require "kong.tools.utils"
...
+local public_utils = require "kong.utils.public"
 
 local string_find = string.find
 local ngx_req_get_headers = ngx.req.get_headers
 local ngx_req_read_body = ngx.req.read_body
-local ngx_req_get_post_args = ngx.req.get_post_args
 local ngx_req_get_uri_args = ngx.req.get_uri_args
 local ngx_req_get_body_data = ngx.req.get_body_data
 
+local get_post_args = public_utils.get_post_args
```
Comment (thibaultcha) [inline kong/plugins/aws-lambda/handler.lua]: (Such cached values shouldn't be required since `public_utils` is not a global)

File: kong/utils/public.lua [hunk 3]
```diff
@@ -0,0 +1,25 @@
...
+
+
+do
+  local ngx_req_get_post_args = ngx.req.get_post_args
+
+  function _M.get_post_args()
+    local ok, res, err = pcall(ngx_req_get_post_args)
+
+    if not ok or err then
+      ngx_log(ERR, "could not get body args: ", err)
```
Comment (thibaultcha) [inline kong/utils/public.lua]: I think we are missing the case where the error is in `res`?

I think we should either your original approach, either if you were worried about my comment (which was mentioned as low priority), then what I meant was:

```lua
if not ok then
  ngx_log(ERR, "could not get body args: ", res)
  return {}
end

if not res then
  ngx_log(ERR, "could not get body args: ", err)
  return {}
end

return res
```

Comment (p0pr0ck5) [inline kong/utils/public.lua]: Done, based on the original idea.

File: kong/plugins/aws-lambda/handler.lua (hunk 2 above)
Comment (p0pr0ck5) [inline kong/plugins/aws-lambda/handler.lua]: Done.

**Comment by thibaultcha** [comment]
Thanks!
