### PR TITLE
hotfix(core) handle anon reports in authenticated requests

### LINKED ISSUE #2756: 0.11.0rc2: failed to iterate over APIs plugins
### Summary

When trying to iterate over APIs plugins it fails.
Error is 
```
kong-01.dev      | 2017/08/01 15:44:02 [error] 318#0: *7356 lua entry thread aborted: runtime error: /usr/local/share/lua/5.1/kong/core/plugins_iterator.lua:74: attempt to index local 'schema' (a nil value)
kong-01.dev      | stack traceback:
kong-01.dev      | coroutine 0:
kong-01.dev      |      /usr/local/share/lua/5.1/kong/core/plugins_iterator.lua: in function '(for generator)'
kong-01.dev      |      /usr/local/share/lua/5.1/kong.lua:348: in function 'access'
kong-01.dev      |      access_by_lua(nginx-kong.conf:89):2: in function <access_by_lua(nginx-kong.conf:89):1>, client: 172.20.1.18, server: kong, request: "PUT /v1/session HTTP/1.1", host: "dev-api.localapp.ch"
```

After looking at the commit [baf69f1f230c77300f3a94be7fc72643caef1e9d](https://github.com/Mashape/kong/commit/baf69f1f230c77300f3a94be7fc72643caef1e9d#diff-fb54747188fbb9d5cd6fff69c7ce260b) I supposed the code perf optimisation failed at some point.

Replacing the file with the [previous version](https://github.com/Mashape/kong/blob/0.11.0rc1/kong/core/plugins_iterator.lua) and reloading kong did the trick.

### Steps To Reproduce

1. Created an API (opened) without plugins configuration + an API (restricted) with a JWT plugin (+ a consumer of course)
2. Did try to use the opened API worked well
3. Did try to use the restricted API it failed with unexpected error
4. Replacing kong/core/plugins_iterator.lua with the 0.11.0rc1 version solved the problem

### Additional Details & Logs

- Kong version 0.11.0rc2
- Operating System => Docker kong:0.10.3 + removed kong 0.10.3 + installed 0.11.0rc2

### PR DESCRIPTION
**Pull request by thibaultcha**
If a request is authenticated via one of the authentication plugins
(key-auth, basic-auth, jwt, etc...) and if `anonymous_reports` are
enabled, Kong errors out and returns an HTTP 500 error.

This was not detected by our test suite since tests are run with
`anonymous_reports` **disabled**.

Context:

The new runloop introduced in baf69f1f230c77300f3a94be7fc72643caef1e9d
assumes that plugins always have a schema (which is a correct assumption
to make). However, the `anonymous_reports` feature is implemented as such
a plugin for legacy reasons. Furthermore, it is implemented *without* a
schema, which is an oversight from a legacy contribution. As such, once
a request is authenticated, the new runloop evaluates plugins by
considering their `schema.no_consumer` property (if set, then the
runloop does not run those plugins, since a Consumer is authenticated).
However, because the anonymous_reports plugin has no such schema, the
indexation fails:

kong/core/plugins_iterator.lua:74: attempt to index local 'schema' (a nil value)

This commit contains:

* a regression test
* a condition to check for the existence of a plugin's schema before
  indexing its `no_consumer` field
* an empty schema for the anonymous_reports plugin (since it is a
  requirement for all other plugins to have one, as enforced in the code)

Fix #2756

### CODE REVIEW

File: spec/02-integration/05-proxy/03-plugins_triggering_spec.lua [hunk 1]
```diff
@@ -160,4 +162,84 @@ describe("Plugins triggering", function()
...
+
+    teardown(function()
+      if client then
+        client:close()
+      end
+
+      helpers.stop_kong()
+    end)
+
+    it("", function()
```
Comment (kikito) [inline spec/02-integration/05-proxy/03-plugins_triggering_spec.lua]: `it("runs without causing an internal error")`, maybe?
