### PR TITLE
CI fixes, cassandra setup, closes #784

### LINKED ISSUE #784: [CI] use Apache's archives to download Cassadra
Our current CI platforms use mirrors that only maintain the latest Cassandra release. As soon as a new version is released, CI tests will fail because they cannot download Cassandra (the link changes).

CI platforms should use [Apache's archives](https://archive.apache.org/dist/cassandra) like other projects (like `ccm`) do to retrieve the Cassandra version we want to run our tests against.

### PR DESCRIPTION
**Pull request by Tieske**
- gets cassandra from the archives
- oauth2 test typos
- better logging of port blocking, including a timeout option (disabled for now, not changing behaviour)

### CODE REVIEW

File: kong/cli/utils/signal.lua [hunk 1]
```diff
@@ -241,6 +257,7 @@ end
 -- @return A boolean: true for success, false otherwise
 function _M.send_signal(args_config, signal)
   -- Make sure nginx is there and is openresty
+  local port_timeout = 0   --Default 0 to not change current behaviour. TODO: make timeout configurable (note: this is a blocking timeout!)
```
Comment (thibaultCha) [inline kong/cli/utils/signal.lua]: I don't think this needs to be configurable, it's too low level for users to even care (in fact, other configurable properties in the configuration are already being completely ignored by users, because already too low level). We just need to find a reasonable value (maybe 1 or 2 seconds) and stick to it.

**Comment by Tieske** [comment]
updated the timeout to 1 second

**Comment by Tieske** [comment]
no more comments received, so merging this.
