### PR TITLE
hotfix(cache): removes deadlocks when cache callbacks error

### LINKED ISSUE #2186: Cache lock problem
Hi there,

I am developing a custom plugin and try to use the cache, but I am having an issue with it:

```
2017/03/10 01:23:17 [error] 62#0: *125 [lua] database_cache.lua:153: get_or_set(): failed to acquire cache lock: timeout, client: 10.66.100.1, server: kong, request: "GET /toto HTTP/1.1"
```

Here is a quick snippet of the code I have:

```
local function load_role(role)
   local dao_role, err = singletons.dao.sh_roles:find_all {role = role}

   if #dao_role ~= 1 or err then
      return responses.send(401, "Bad token, not a valid role")
   end

   return dao_role[1]
end

local function do_check_roles(roles)
   local verb = ngx.req.get_method()
   local uri = ngx.var.uri

   for k,role in pairs(roles) do
      local dao_role = cache.get_or_set("roles."..role, nil, load_role, role)
      --dao_role = load_role(role)                                                                                                                                                                                                         

      for ruri,verbs in pairs(dao_role.access) do
         if string.match(uri, '^' .. ruri .. '$') then
            if has_value(verbs, verb) then
               return true
            end
         end
      end
   end

   return false, {status = 401, message = "Permission denied"}
end

```


The error does not happen straight away but only seems to be triggered after the third time and only in the case where the callback is returning directly a 401 response.

### Steps To Reproduce

1. Add an api
2. Map a custom plugin to this api
3. Query kong about two or three times and that should trigger the bug

### Additional Details & Logs

- Kong 0.10.0 (docker image)


Logs:

```
2017/03/10 01:27:17 [debug] 61#0: *68 [lua] base_plugin.lua:17: access():  executing plugin "roles-filtering-plugin": access
2017/03/10 01:27:17 [debug] 61#0: *68 [lua] base_plugin.lua:21: header_filter():  executing plugin "roles-filtering-plugin": header_filter
2017/03/10 01:27:17 [debug] 61#0: *68 [lua] base_plugin.lua:25: body_filter():  executing plugin "roles-filtering-plugin": body_filter
2017/03/10 01:27:17 [debug] 61#0: *68 [lua] base_plugin.lua:25: body_filter():  executing plugin "roles-filtering-plugin": body_filter
2017/03/10 01:27:17 [debug] 61#0: *68 [lua] base_plugin.lua:29: log():  executing plugin "roles-filtering-plugin": log
2017/03/10 01:27:17 [info] 61#0: *68 client 10.66.100.1 closed keepalive connection
2017/03/10 01:27:19 [debug] 61#0: *129 [lua] base_plugin.lua:17: access():  executing plugin "roles-filtering-plugin": access
2017/03/10 01:27:19 [info] 61#0: *133 client 127.0.0.1 closed keepalive connection
2017/03/10 01:27:19 [info] 61#0: *131 client 127.0.0.1 closed keepalive connection
2017/03/10 01:27:19 [info] 61#0: *134 client 127.0.0.1 closed keepalive connection
2017/03/10 01:27:20 [debug] 62#0: *152 [lua] cluster.lua:20: log(): [cluster] auto-joining
2017/03/10 01:27:22 [info] 61#0: *161 client 127.0.0.1 closed keepalive connection
2017/03/10 01:27:22 [info] 61#0: *162 client 127.0.0.1 closed keepalive connection
2017/03/10 01:27:22 [info] 61#0: *165 client 127.0.0.1 closed keepalive connection
2017/03/10 01:27:23 [debug] 62#0: *182 [lua] cluster.lua:20: log(): [cluster] auto-joining
2017/03/10 01:27:24 [error] 61#0: *129 [lua] database_cache.lua:153: get_or_set(): failed to acquire cache lock: timeout, client: 10.66.100.1, server: kong, request: "GET /toto HTTP/1.1", host: "10.66.100.101"
2017/03/10 01:27:24 [error] 61#0: *129 lua entry thread aborted: runtime error: /plugins/kong/plugins/roles-filtering-plugin/handler.lua:93: attempt to index local 'dao_role' (a nil value)
stack traceback:
coroutine 0:
	/plugins/kong/plugins/roles-filtering-plugin/handler.lua: in function 'do_check_roles'
	/plugins/kong/plugins/roles-filtering-plugin/handler.lua:123: in function 'access'
	/usr/local/share/lua/5.1/kong.lua:256: in function 'access'
	access_by_lua(nginx-kong.conf:81):2: in function <access_by_lua(nginx-kong.conf:81):1>, client: 10.66.100.1, server: kong, request: "GET /toto HTTP/1.1", host: "10.66.100.101"
2017/03/10 01:27:25 [info] 61#0: *192 client 127.0.0.1 closed keepalive connection
2017/03/10 01:27:25 [info] 61#0: *191 client 127.0.0.1 closed keepalive connection




stack traceback:
coroutine 0:
	/plugins/kong/plugins/roles-filtering-plugin/handler.lua: in function 'do_check_roles'
	/plugins/kong/plugins/roles-filtering-plugin/handler.lua:123: in function 'access'
	/usr/local/share/lua/5.1/kong.lua:256: in function 'access'
	access_by_lua(nginx-kong.conf:81):2: in function <access_by_lua(nginx-kong.conf:81):1>, client: 10.66.100.1, server: kong, request: "GET /toto HTTP/1.1", host: "10.66.100.101"

```

### PR DESCRIPTION
**Pull request by Tieske**
Main cause is exiting early on error conditions, when the lock has not
yet been released. It occurs both in the `get_or_set` method itself as
well as in the callbacks all over the code base.

### Issues resolved

Fix #2186

### CODE REVIEW

File: kong/tools/database_cache.lua [hunk 1]
```diff
@@ -4,6 +4,9 @@ local json_decode = require("cjson.safe").decode
 local cache = ngx.shared.cache
 local ngx_log = ngx.log
 local gettime = ngx.now
+local utils = require "kong.tools.utils"
```
Comment (thibaultcha) [inline kong/tools/database_cache.lua]: By convention across the entire code base, requires go at the top.

File: kong/tools/database_cache.lua [hunk 2]
```diff
@@ -159,30 +165,42 @@ function _M.get_or_set(key, ttl, cb, ...)
...
-  if value == nil then
-    -- Get from closure
-    value, err = cb(...)
-    if err then
-      return nil, err
+  if value ~= nil then
+    -- shm cache success
+    local ok, lerr = lock:unlock()
+    if not ok and lerr then
+      ngx_log(ngx.ERR, "failed to unlock: ", lerr)
```
Comment (thibaultcha) [inline kong/tools/database_cache.lua]: Those messages need more contexts as well:

```lua
ngx_log(ngx.ERR, "[db cache] failed to unlock mutex: ", lerr)
```

File: kong/tools/database_cache.lua [hunk 3]
```diff
@@ -159,30 +165,42 @@ function _M.get_or_set(key, ttl, cb, ...)
...
+      ngx_log(ngx.ERR, err)
     end
   end
 
-  local ok, err = lock:unlock()
-  if not ok and err then
-    ngx_log(ngx.ERR, "failed to unlock: ", err)
+  local ok, lerr = lock:unlock()
+  if not ok and lerr then
+    ngx_log(ngx.ERR, "failed to unlock: ", lerr)
```
Comment (thibaultcha) [inline kong/tools/database_cache.lua]: ditto:
```lua
ngx_log(ngx.ERR, "[db cache] failed to unlock mutex: ", lerr)
```

File: kong/tools/database_cache.lua (hunk 2 above)
Comment (thibaultcha) [inline kong/tools/database_cache.lua]: This is why we often have such a function at the beginning of a module:
```lua
local function log(lvl, ...)
  return ngx.log(lvl, "[module_name] ", ...)
end
```

File: kong/tools/database_cache.lua [hunk 4]
```diff
@@ -159,30 +165,42 @@ function _M.get_or_set(key, ttl, cb, ...)
...
+  end
+
+  if value[1] ~= nil then
+    -- only return first value, as on each next lookup the cache will
+    -- also only return a single value
+    return value[1]
   end
 
-  return value
+  return unpack(value)
```
Comment (thibaultcha) [inline kong/tools/database_cache.lua]: A few things:

- in places where we hit a lock error, we just `return`
- not in the new places L.194 and L.188
- here on L.203, we might return `nil, nil, ...`

All of these points are a problem because the way we check for errors after `get_ot_set()` is like this:
```
local thing, err = cache.get_or_set(...)
if err then
  return responses.send_HTTP_INTERNAL_SERVER_ERROR(err)
end
```

Hence, I feel like we should always return an error to the caller if such happens in `get_or_set()`, instead of failing at a later point in the caller's code and make tracing of the error harder.

I think the main issue is the callers are not handling cache miss properly (missing entity from the DB hit), and they should, and lock issues should be reported internally only. But this is the fastest change we can do to address it right now.

Comment (Tieske) [inline kong/tools/database_cache.lua]: @thibaultcha Not sure I'm following your reasoning. Hence here's what I did and why;

> in places where we hit a lock error, we just return

That is for creating and acquiring the lock, non-recoverable, so exit

> not in the new places L.194 and L.188

We already got the info from the db, so recoverable, the current request can be completed, yet the error on the 'process level' (locking/setting) is properly logged => the error is a `get_or_set` error

>here on L.203, we might return nil, nil, ...

This allows the callback to return multiple return values in case of errors to distinguish between for example "return a nil + error" result or "terminate request with a 500" result  => the error is a caller error and is dealt with by the caller.
There is one occasion where "nil+error_msg+status_code" is returned for example

> Hence, I feel like we should always return an error to the caller if such happens in get_or_set(), instead of failing at a later point in the caller's code and make tracing of the error harder.

The way I wrote it now was to allow the caller to determine what error to return in what format, and to deal with it as well. Also for tracing, you want the error to be logged from the calling code (line numbers and function names), dealing with it from `get_or_set` would make tracing a lot harder as you wouldn't know where it originated.

Makes sense? Did I miss something?

Comment (thibaultcha) [inline kong/tools/database_cache.lua]: > This allows the callback to return multiple return values

got that, but now if a callback does not properly return an error, we have:

```
return nil, [nil]
```

And the caller does:
```lua
local _, err = get_or_set()
if err then -- nil, because this is the [nil] one returned by the get_or_set cb

end

-- we missed our chance to return HTTP 500 because the callback errored
```

Comment (Tieske) [inline kong/tools/database_cache.lua]: But then still something further down will go awry, because no data was returned. So it will surface as a bug anyway.

And this situation will always exist, as the callback should be able to return `nil` for the data. And then `return nil` (same as `return nil, nil`) is a valid non-error response. So the only way to test for an error will always be on `err`.

Comment (Tieske) [inline kong/tools/database_cache.lua]: @thibaultcha verified all `get_or_set` accesses again, fixed one occurrence where a wrong error was thrown/logged.

imo good to go now.

File: kong/plugins/key-auth/handler.lua [hunk 5]
```diff
@@ -132,8 +132,11 @@ function KeyAuthHandler:access(conf)
   if not ok then
     if conf.anonymous ~= "" then
       -- get anonymous user
-      local consumer = cache.get_or_set(cache.consumer_key(conf.anonymous),
-                       nil, load_consumer, conf.anonymous, true)
+      local consumer, err = cache.get_or_set(cache.consumer_key(conf.anonymous),
+                            nil, load_consumer, conf.anonymous, true)
+      if err then
+        responses.send_HTTP_INTERNAL_SERVER_ERROR(err)
+      end
```
Comment (thibaultcha) [inline kong/plugins/key-auth/handler.lua]: I guess the issue I wanted to point out in our talk is more how plugins can sometimes expect the cached value to always be present without considering it might just not exist in the data store. Agreed, if we found a key credential in the datastore, we should have a Consumer attached to it as well.

In this case, maybe we want to throw a 500, or maybe we'd rather handle that case just like the missing credentials above, and return HTTP 403. So two things:

1. Should we return HTTP 403 here if no Consumer was retrieved from the DB?
2. Are we sure no other plugins is guilty of the behavior I described above? aka always assuming we'll retrieve an entity from `cache.get_or_set()`?

Some more background on the actual issue if such a case happens in this plugin:

If the `cache.get_or_set` call returns `nil, nil`, then the `set_consumer` function will error out when trying to index `consumer.id`. This will throw a Lua error, bother the Kong user, and return an HTTP 500 to the client making this call. Instead, see L.108 to L.110, where the plugin handles the case where no credential was found in the DB (request provided with authentication, but such authentication is invalid), and thus, replies HTTP 403 to the client.

Comment (Tieske) [inline kong/plugins/key-auth/handler.lua]: > Should we return HTTP 403 here if no Consumer was retrieved from the DB?

This case is not a 403, but a 500. A consumer was configured as "anonymous" but with a bad uuid (was never there), or with a consumer that was later deleted.

Hence a configuration error, and hence a 500 imo. This is also the quicker route to the maintainers that something is wrong with the configuration

> Are we sure no other plugins is guilty of the behavior I described above? aka always assuming we'll retrieve an entity from `cache.get_or_set()`?

All callbacks properly return the error, that's what I checked. But then still, this behaviour is a contract that the caller itself created between the callback he provided and his result handling code. It is not a responsibility of the caching mechanism to handle this.

Anyway, this is probably going away with an lru cache anyway, the way we discussed it.

**Comment by rocketspacer** [comment]
Can you help merge the fix to kong **0.9.x**
