### PR TITLE
fix(oauth2) remove unique constraint on client_secret

### LINKED ISSUE #1972: [OAuth2] Secret unique check
Kong: 0.8.3

If I try to add an OAuth2 application with a client_secret that already exists it fails. What is the motivation for this behavior? IMHO, only client_id must be unique, not secrets.

I haven't tried with new versions but code seems not to be changed:
https://github.com/Mashape/kong/blob/master/kong/plugins/oauth2/daos.lua#L37

Thanks

### PR DESCRIPTION
**Pull request by p0pr0ck5**
### Summary

Remove the unique constraint on client_secret in the oauth2_credentials table. There appears to be no need to hold this constraint; indeed, no other authentication plugins take this approach (apart from JWT, which builds logic around maintaining a unique key).

### Full changelog

* remove unique constraint on client_secret

### Issues resolved

Fix #1972

### CODE REVIEW

File: kong/plugins/oauth2/migrations/postgres.lua [hunk 1]
```diff
@@ -151,5 +151,14 @@ return {
         if err then return err end
       end
     end
+  },
+  {
+    name = "2017-04-24-oauth2_client_secret_not_unique",
+    up = [[
+      ALTER TABLE oauth2_credentials DROP CONSTRAINT oauth2_credentials_client_secret_key;
```
Comment (bungle) [inline kong/plugins/oauth2/migrations/postgres.lua]: Should we have `IF EXISTS` here (I'm not sure, but I doesn't hurt)?

**Comment by p0pr0ck5** [comment]
@bungle the migrations now includes the `IF EXISTS` clause.

**Comment by p0pr0ck5** [comment]
crap, missed the `hold merge` label. @thibaultcha do you want me to revert this?

**Comment by thibaultcha** [comment]
No that's fine, I think we should have a `status/ready` and a `status/ready (hold merge)` distinction
