### PR TITLE
fix(plugin) fixes a wrong constant for the request size limit plugin

### LINKED ISSUE #1415: Request Size Limiting Plugin Payload Size Miscalculation
### Summary

The documentation makes it clear that the allowed payload size should be in megabytes, 128 should mean 128,000,000 bytes.
https://getkong.org/plugins/request-size-limiting/

When we use this plugin we find that 128 will actually give a size limit of 12,800,000 bytes.
If we look at the code the offending line is quite clear:
https://github.com/Mashape/kong/blob/master/kong/plugins/request-size-limiting/handler.lua#L14
I believe this number multiplied by the payload size should have an extra 0.

### Steps To Reproduce

1. Add a request size limiting plugin to your API 
2. Set the request size limit to 10
3. Create a file called test in your home folder of size 9MB.
4. Run: `curl -X "POST" -i --data "@~/test" http://localhost:8000/{your api request path}`
5. The request is rejected.

### Additional Details & Logs

- Kong version: 0.8.3
- Operating System: CentOS

### PR DESCRIPTION
**Pull request by Tieske**
### Summary

constant for mb was 100.000 instead of 1.000.000 causing request to be rejected falsy.

### Full changelog

* fix wrong constant in request-size-limit plugin

### Issues resolved

Fixes #1415

### CODE REVIEW

File: kong/plugins/request-size-limiting/handler.lua [hunk 1]
```diff
@@ -2,16 +2,16 @@
...
-local stringy = require "stringy"
+local strip = require("pl.stringx").strip
 
 local RequestSizeLimitingHandler = BasePlugin:extend()
 
 RequestSizeLimitingHandler.PRIORITY = 950
 
 local function check_size(length, allowed_size, headers)
-  local allowed_bytes_size = allowed_size * 100000
+  local allowed_bytes_size = allowed_size * 1000000
```
Comment (thibaultCha) [inline kong/plugins/request-size-limiting/handler.lua]: I find it much more convenient and requiring less cognitive load (as well as much less error prone) to declare constants representing size (including MBs) like so:
```lua
local CONST_NAME = X * 10^6 -- here X being 1
```
Then use `CONST_NAME` in the module's function.

Comment (Tieske) [inline kong/plugins/request-size-limiting/handler.lua]: updated, including a linter fix to make ci run

File: kong/plugins/request-size-limiting/handler.lua [hunk 2]
```diff
@@ -2,16 +2,18 @@
 
 local BasePlugin = require "kong.plugins.base_plugin"
 local responses = require "kong.tools.responses"
-local stringy = require "stringy"
+local strip = require("pl.stringx").strip
+
+local MEGABYTE = 10^6
```
Comment (thibaultCha) [inline kong/plugins/request-size-limiting/handler.lua]: Should be `2^20` btw
