### PR TITLE
fix(plugins) add unique constraint to id field

### LINKED ISSUE #2227: Redundant kong plugin_id
### Summary

In my case, i want to delete an plugin. From documentation here https://getkong.org/docs/0.9.x/admin-api/ , i find that it only have 2 attr, plugin_id and api_id. But the problem, i have some plugin with same api_id and plugin_id.

Is it normal to have same plugin_id and how i can delete the plugin with that condition ?

Thanks

### Additional Details & Logs
This is sample of my plugins
```
{
	"api_id": "0cd4a0d3-2e41-4b51-945a-eb06adbe8d1e",
	"id": "0cd4a0d3-2e41-4b51-945a-eb06adbe8d1e",
	"created_at": ** ,
	"enabled": false,
	"name": "statsd",
	"config": {
		"host": "localhost",
		"timeout": 10000,
		"metrics": ["*"],
		"port": *
	}
}, {
	"api_id": "0cd4a0d3-2e41-4b51-945a-eb06adbe8d1e",
	"id": "0cd4a0d3-2e41-4b51-945a-eb06adbe8d1e",
	"created_at": ** ,
	"enabled": false,
	"name": "****",
	"config": {
		"percentage": 0,
		"upstream_host": ""
	}
}
```

- Kong version (0.9.5)
- Operating System (CentOS 6.5)
- Database (Postgres 9.4)

### PR DESCRIPTION
**Pull request by p0pr0ck5**
### Summary

The compound primary key, coupled with a lack of unique constraint
on id, allows for duplicate plugin UUIDs, breaking expected behavior.
This commit adds a unique constraint in the Kong schema, and directly
to the Postgres table definition via a migration.

### Full changelog

* fix(plugins) add unique constraint to id field

### Issues resolved

Fix #2227

### CODE REVIEW

**Comment by p0pr0ck5** [comment]
I am unsure why the `plugins` primary_key is `id, name`; the commit history surrounding both the migrations and the schema are opaque and do not explain the reasoning behind this decision (or in the case of the kong schema, the change from a primary_key of `id` to a compound `id, name`; see 59d576dd4e0d28cecf2f6fd4996567b17ba9bb6a).

File: spec/02-integration/03-admin_api/02-apis_routes_spec.lua [hunk 1]
```diff
@@ -1,28 +1,38 @@
...
+    })
     client = assert(helpers.admin_client())
   end)
   teardown(function()
     if client then client:close() end
     helpers.stop_kong()
   end)
 
-  describe("/apis", function()
+  describe("/apis ", function()
```
Comment (thibaultcha) [inline spec/02-integration/03-admin_api/02-apis_routes_spec.lua]: :(

**Comment by p0pr0ck5** [comment]
We want to make the migration a bit more human friendly for the required manual cleanup.
