### PR TITLE
fix(router) do not match another API with a longer URI

### LINKED ISSUE #2662: Kong doesn't match the longest uri when multiple uris are defined on an api
### Summary

If two (or more) APIs have uris that match the incoming uri, Kong will route to the API with the longest uri, even if that uri is not the one that matches.

### Steps To Reproduce

1. Fresh Kong install
2. Setup routes: 
`curl -X POST -H "Content-Type: application/json" -d '{"name":"a", "uris":"/a,/cccccc", "upstream_url":"https://google.com"}' localhost:8001/apis`
`curl -X POST -H "Content-Type: application/json" -d '{"name":"b", "uris":"/a/bb", "upstream_url":"https://example.com"}' localhost:8001/apis`
3. `curl localhost:8000/a/bb/123` will route to google.com instead of example.com

Note:
- If `/a` and `/ccccc` are defined as separate APIs, `curl localhost:8000/a/bb/123` will route to example.com instead.
- Also, if you replace `/a,/ccccc` with `/a,/cc` in the first route, `curl localhost:8000/a/bb/123` will route to example.com.
- Therefore, I think that there is an issue with how Kong is calculating the length of a matching uri. I'm not familiar with the code, but it seems like when an API matches, Kong thinks the longest uri on that API is the length of the match.

### Additional Details & Logs

- Kong version 0.10.3

### PR DESCRIPTION
**Pull request by thibaultcha**
When matching URIs, we iterate over a list of APIs, and not a list of
URIs (for various, performance reasons, although a refactor of the
router is scheduled with some performance improvements later on).
This list of APIs is sorted per URI length. But an API can have more
than one URI. As such, the router can potentially evaluate an API with a
very long URI, and a much shorter one that matches the request URI,
instead of a following API which would be an exact match for that API.

To fix this, we sort our deserialized list of URIs to iterate on in the
select method, and if we do have a match, we conserve the URI that was
matched, to check if it belongs to the right API at API match time.

Fix #2662

### CODE REVIEW

File: spec/01-unit/11-router_spec.lua [hunk 1]
```diff
@@ -605,6 +605,25 @@ describe("Router", function()
           assert.same(use_case[#use_case], api_t.api)
         end)
       end)
+
+      it("does not falsly match another API which has a longer [uri]", function()
```
Comment (p0pr0ck5) [inline spec/01-unit/11-router_spec.lua]: "falsely" (alternatively, "incorrectly")

Comment (p0pr0ck5) [inline spec/01-unit/11-router_spec.lua]: also, brackets around `uri`?

**Comment by thibaultcha** [comment]
The brackets are in all the test titles for this suite.
