### PR TITLE
fix(api) lookup entities by secondary field as uuid

### LINKED ISSUE #2415: entity lookups on `xxx_or_id` do not work as expected
### Summary

Whenever those functions are used, if the `xxx` is a `uuid` then they fail. Most common case is the `consumer` entity, but others suffer from the same problem.

### Resolution

Whenever the key value is a `uuid` and it is not found in the entities `id` field, a second search based on the `xxx` field should be tried as a fallback.

Because uuids are unique by definition this should not pose a problem.

### PR DESCRIPTION
**Pull request by Tieske**
when the name/key/whatever field is formatted as a uuid Kong
would assume that field to be the `id` field. This change will
make it first try the `id` field in that case, and then the
alternative field.

### Issues resolved

Fixes #2415

### CODE REVIEW

File: kong/api/crud_helpers.lua [hunk 1]
```diff
@@ -5,16 +5,43 @@ local app_helpers = require "lapis.application"
 
 local _M = {}
 
+--- Will look up a value in the dao.
+-- Either by `id` field or by the field named by 'alternate_field'. If the value is NOT
+-- a uuid, then by the 'alternate_field'. If it is a uuid then it will first try
```
Comment (p0pr0ck5) [inline kong/api/crud_helpers.lua]: pedantic note: "a uuid" to me implies that the string we found is a UUID we generated. this could be clarified by noting the string "looks like a uuid" as opposed to is "_a_ uuid"

File: kong/api/crud_helpers.lua [hunk 2]
```diff
@@ -5,16 +5,43 @@ local app_helpers = require "lapis.application"
...
+-- @param alternate_field the field to use if it is not a uuid, or not found in `id`
+function _M.find_by_id_or_field(dao, filter, value, alternate_field)
+  filter = filter or {}
+  local is_uuid = utils.is_valid_uuid(value)
+  filter[is_uuid and "id" or alternate_field] = value
+
+  local rows, err = dao:find_all(filter)
+  if err then
+    return nil, err
+  elseif is_uuid and not next(rows) then
```
Comment (p0pr0ck5) [inline kong/api/crud_helpers.lua]: should be `#rows == 0` instead of `next(rows)`?

File: kong/api/crud_helpers.lua (hunk 1 above)
Comment (Tieske) [inline kong/api/crud_helpers.lua]: uuid's have a specific format and can be validated to conform to that format. Though our check is not doing that because in the past we created bad uuids.

File: kong/api/crud_helpers.lua (hunk 2 above)
Comment (Tieske) [inline kong/api/crud_helpers.lua]: same?

Comment (p0pr0ck5) [inline kong/api/crud_helpers.lua]: yep, same. style + good practice + consistency with other uses (probably worth a cleanup PR to remove that anti-pattern throughout the codebase).
