### PR TITLE
fix(core) returning appropriate headers in error pages

### LINKED ISSUE #1552: OpenResty version exposed when request URL is to large
### Summary

When sending an invalid request with a URL that is too long, nginx/OpenResty returns a 414 error code which is not handled by Kong's error handler (which is only configured to handle 50x errors). The expectation is that Kong's error handler also captures this, instead of exposing information about OpenResty and it's version. The information is not only provided in the HTML body, but also on the `Server` header (which typically has Kong's version number instead)

### Steps To Reproduce

1. Call an API with a URL that is too long, e.g., `http://{KONG_HOST}:{KONG_PORT}/{REPEAT SAME CHARACTER AT LEAST 10k TIMES}`

### Additional Details & Logs

- Kong version (`0.8.3`)
- Kong configuration (Default configuration file, regardless on what APIs are configured if any)
- Ubuntu 14.04

### LINKED ISSUE #1553: OpenResty version exposed when hitting /50x resource
### Summary

When sending an request to the `/50x` of the server, a `404` error is returned with the version of OpenResty. The expectation is that Kong's error handler also captures this, instead of exposing information about OpenResty and it's version. The information is not only provided in the HTML body, but also on the `Server` header (which typically has Kong's version number instead)

### Steps To Reproduce

1. Call `http://{KONG_HOST}:{KONG_PORT}/50x`

### Additional Details & Logs

- Kong version (`0.8.3`)
- Kong configuration (Default configuration file, regardless on what APIs are configured if any)
- Ubuntu 14.04

### PR DESCRIPTION
**Pull request by thefosk**
### Full changelog

* Properly return the correct Kong headers on 40x and 50x errors.

### Issues resolved

Fix #1552 and #1553.

### CODE REVIEW

File: spec/02-integration/05-proxy/01-resolver_spec.lua [hunk 1]
```diff
@@ -358,5 +358,6 @@ describe("Resolver", function()
       }
     })
     assert.res_status(414, res)
+    assert.match("kong", res.headers["server"])
```
Comment (thibaultcha) [inline spec/02-integration/05-proxy/01-resolver_spec.lua]: needs to come from the `meta` module just like other tests

**Comment by thefosk** [comment]
@thibaultcha using `meta` in test now.
