### PR TITLE
fix(dao) allow escaped commas in arrays

### LINKED ISSUE #2780: Comma Character in URI Regex Incorrectly Parsed
### Summary

Comma characters in URI regular expressions are not correctly parsed; Kong sees this character as an entity split, not part of the expression.

### Steps To Reproduce

1. Add API object with regular expression containing comma

```
$ curl localhost:8001/apis -d name=test -d upstream_url=http://httpbin.org -d uris="/foo/\d{1,3}"
{"uris":"uri with value '3}' is invalid: must be prefixed with slash"}
```

### Additional Details & Logs

- Kong version (`$ kong version`)

0.11.0rc2

- Kong debug-level startup logs (`$ kong start --vv`)

N/A

- Kong error logs (`<KONG_PREFIX>/logs/error.log`)

N/A

- Kong configuration (registered APIs/Plugins & configuration file)

No entities, no configuration changes.

- Operating System

Trusty

### PR DESCRIPTION
**Pull request by hishamhm**
Support using `\,` for representing a `,` character in a comma-separated array, without using it as a separator. This allows one to use commas when entering URIs using the PCRE regex syntax `{n,m}` for `n`-to-`m` repetitions. For example:

```
$ curl localhost:8001/apis -d name=test -d upstream_url=http://httpbin.org -d uris='/foo/\d{1\,3},/bar'
```

Fixes #2780.

### CODE REVIEW

File: kong/dao/schemas_validation.lua [hunk 1]
```diff
@@ -117,9 +117,16 @@ function _M.validate_entity(tbl, schema, options)
               is_valid_type = bool == "true" or bool == "false"
               t[column] = bool == "true"
             elseif v.type == "array" then
-              t[column] = utils.strip(t[column]) == "" and {} or utils.split(t[column], ",") -- Handling empty arrays
+              -- handle escaped commas inside the comma-separated array
+              -- by flipping them into a \0 and then back
+              local escaped = t[column]:gsub("\\,", "\0")
+              if utils.strip(t[column]) == "" then
+                t[column] = {} -- Handling empty arrays
+              else
```
Comment (thibaultcha) [inline kong/dao/schemas_validation.lua]: style: mind adding a line break above this `else`?

File: spec/01-unit/006-schema_validation_spec.lua [hunk 2]
```diff
@@ -292,6 +292,22 @@ describe("Schemas", function()
...
+          }
+        }
+
+        -- It should also strip the resulting strings
+        local values = { array = "hello\\, world,goodbye world\\,,/hello/\\d{1\\,3}" }
+
+        local valid, err = validate_entity(values, s)
+        assert.True(valid)
+        assert.falsy(err)
+        assert.same({"hello, world", "goodbye world,", "/hello/\\d{1,3}"}, values.array)
```
Comment (thibaultcha) [inline spec/01-unit/006-schema_validation_spec.lua]: Would you agree that this test could be made more readable? It also says it will strip the resulting strings, but is not doing so. For the sake of the tests' atomicity, it might be a good thing though!

Here is a proposed update that just makes the test more readable (avoids double escaping because of Lua strings) (the rest is just more updated style/test message that is - granted - not followed by the rest of this outdated test suite...):

```diff
diff --git a/spec/01-unit/006-schema_validation_spec.lua b/spec/01-unit/006-schema_validation_spec.lua
index cc1ca8d7..8f2f8156 100644
--- a/spec/01-unit/006-schema_validation_spec.lua
+++ b/spec/01-unit/006-schema_validation_spec.lua
@@ -293,20 +293,26 @@ describe("Schemas", function()
         assert.same({"hello", "world"}, values.array)
       end)
 
-      it("should handle escaped commas in comma-separated arrays", function()
+      it("preserves escaped commas in comma-separated arrays", function()
+        -- Note: regression test for arrays of PCRE URIs:
+        -- https://github.com/Mashape/kong/issues/2780
+
         local s = {
           fields = {
-            array = {type = "array"}
+            array = { type = "array" }
           }
         }
 
         -- It should also strip the resulting strings
-        local values = { array = "hello\\, world,goodbye world\\,,/hello/\\d{1\\,3}" }
+        local values = {
+          array = [[  hello\, world  ,  goodbye world  ,  /hello/\d{1\,3}  ]]
+        }
 
         local valid, err = validate_entity(values, s)
         assert.True(valid)
         assert.falsy(err)
-        assert.same({"hello, world", "goodbye world,", "/hello/\\d{1,3}"}, values.array)
+        assert.same({ "hello, world", "goodbye world", [[/hello/\d{1,3}]] },
+                    values.array)
       end)
     end)
   end)
```

File: kong/dao/schemas_validation.lua (hunk 1 above)
Comment (hishamhm) [inline kong/dao/schemas_validation.lua]: yep, can do. from the looks of the code I thought the line-break rule applied to larger blocks, not one-liners

Comment (thibaultcha) [inline kong/dao/schemas_validation.lua]: tbh, I would be fine with 1 liner blocks not having a line jump, but keeping it also makes the style simpler to grasp when contributing, and also allows us to build a habit... Not strongly opinionated about it though!

File: spec/01-unit/006-schema_validation_spec.lua (hunk 2 above)
Comment (thibaultcha) [inline spec/01-unit/006-schema_validation_spec.lua]: (I think I read strip as `trim`, but that was not what the comment was about! We should probably keep the strings trimmed instead of doing what this patch does... 😅)

File: kong/dao/schemas_validation.lua (hunk 1 above)
Comment (hishamhm) [inline kong/dao/schemas_validation.lua]: Got it. I tend to use line-breaks as sort of "paragraph" breaks when separating logical parts of a function, so for larger blocks they make sense but in a block like that where it would be the only line break, my reaction looking at the resulting code with the break was that it looked weird, because it draws attention to the "else" more than anything in that block. But this revision is outdated by now :)

File: spec/01-unit/006-schema_validation_spec.lua (hunk 2 above)
Comment (hishamhm) [inline spec/01-unit/006-schema_validation_spec.lua]: I think strip meant the same as trim there. Anyway, I removed the trimming to make sure the unit test tests a single thing, and otherwise applied all your suggested changes! Thanks for the detailed review!

**Comment by thibaultcha** [comment]
(Referencing both the fixed issue and the PR in the commit message is encouraged! Makes it easier to trace the PR when writing the Changelog :) )

File: kong/dao/schemas_validation.lua (hunk 1 above)
Comment (thibaultcha) [inline kong/dao/schemas_validation.lua]: Yeah, I could see that too!

**Comment by hishamhm** [comment]
Will do! Just waiting for Travis.
