### PR TITLE
fix(postgres) ensure APIs created_at has ms precision

### LINKED ISSUE #2899: Kong 0.11.0 URI evaluation order problem
### Summary

I read the Proxy Reference document - https://getkong.org/docs/0.11.x/proxy/, and found that it works differently from the document in some cases.

Issue 1.
The document says - "URI prefixes are always evaluated first". 

But see the source code here,
https://github.com/Mashape/kong/blob/e49cd360693e44e8d3842f62ba92d5c367c3052a/kong/core/router.lua#L666-L691
When req_uri is matched in plain_indexes.uris, it stopped to scan. But if req_uri is matched in uris_prefixes, it breaks only the uris_prefixes's FOR loop. So it will continue to find in uris_regexes.

As a result, the evaluation order becomes below.
	1) full uri match (plain_indexes.uris)
	2) regex match (uris_regexes)
	3) prefix match (uris_prefixes)

Is this the designed behavior?

Issue 2.
The document says - "Kong will evaluate regex URIs based on the order in which they are defined".

But it sounds ambiguous. First time I read that sentences, thought that regex URIs are evaluated by the order of they were registered. But it did not work like that way. I registered 3 APIs, but the match order was seemed like 3 -> 1 -> 2. (I used postgresql.)

Maybe the reason is that when Kong queries api list from DB, it does not use "ORDER BY" condition. SQL queries without "ORDER BY" condition cannot guarantee any order. Therefore Kong users cannot control the order. 

I think duplicated matching cases are rare case, and these issues are not so critical for me. But I thought that sharing the issues are better for Kong project. I hope this will help.

### Steps To Reproduce
Below is my test cases. I registered 5 APIs.

regex-api-1
	uris : /status/(re)
	upstream_url : http://mockbin.org/request/regex1
regex-api-2
	uris : /status/(r)
	upstream_url : http://mockbin.org/request/regex2
regex-api-3
	uris : /(status)
	upstream_url : http://mockbin.org/request/regex3
prefix-api-1
	uris : /status
	upstream_url : http://mockbin.org/request/prefix1
prefix-api-2
	uris : /status/resource
	upstream_url : http://mockbin.org/request/prefix2

And the result was like below. Maybe the result can be different.

"/status" proxied to prefix-api-1
"/status/r" proxied to  regex-api-3
"/status/re" proxied to regex-api-3
"/status/resource" proxied to prefix-api-2
"/status/resource/1" proxied to  regex-api-3

### PR DESCRIPTION
**Pull request by thibaultcha**
APIs are retrieved without an `ORDER BY` clause from the datastore when
building the router. Because of the lack of such a clause in our current
Cassandra schema, we wish to implement sorting by creation date in our
business logic, right before building the router.

However, the PostgreSQL default clause of the APIs `created_at` field
is set to `CURRENT_TIMESTAMP(0)`, which strips ms precision out of the
timestamp. This changes the default timestamp precision to 3 digits so
our sorting attribute (`created_at`) can be meaningful.

This fix is targeting 0.11.1, and as such does not introduce a new
migration to update the default value of `created_at`. This fix will
only have effect for new database schemas.

A second commit will introduce a migration, which, as per our policy,
will be targeted for 0.12.0.

Fix #2899

### CODE REVIEW

**Comment by thibaultcha** [comment]
Currently in the process of addressing the tests failures related to timestamp precision.

File: spec/02-integration/05-proxy/01-router_spec.lua [hunk 1]
```diff
@@ -178,6 +178,55 @@ describe("Router", function()
...
+          name = "api-2",
+          uris = { [[/status/(r)]] },
+          upstream_url = helpers.mock_upstream_url .. "/status/200",
+        },
+        {
+          name = "api-3",
+          uris = { [[/(status)]] },
+          upstream_url = helpers.mock_upstream_url .. "/status/200",
+        },
+      }
```
Comment (hishamhm) [inline spec/02-integration/05-proxy/01-router_spec.lua]: The test tacitly assumes that each entry will take over 1ms to insert?

Comment (thibaultcha) [reply spec/02-integration/05-proxy/01-router_spec.lua]: Indeed. This is almost guaranteed to be the case, but I have a feeling we should do something to enforce it. I was thinking of enforcing a "sleep period" subsequently to each API insertion (at the DAO level), but the idea gave me shivers. Any suggestion?

Comment (hishamhm) [reply spec/02-integration/05-proxy/01-router_spec.lua]: I'd split it into three `insert_apis` calls and insert a 2ms `ngx.sleep` between each.

Comment (thibaultcha) [reply spec/02-integration/05-proxy/01-router_spec.lua]: We could do that, but then we'd leave the door open for a disparity between the test case and the actual DAO's behavior. Currently, none of the two introduces a delay, and the test still succeeds. If we add some delay to the test fixtures setup, we might get a false positive result, but conflicting `created_at` timestamps might still be possible when using the DAO itself. I feel like we should either insert a delay at the DAO level, either not insert it anywhere to avoid getting a false positive.

Comment (hishamhm) [reply spec/02-integration/05-proxy/01-router_spec.lua]: It wouldn't be a false positive: the test would be stating more explicitly what the actual reliability guarantee is. The code would say "if you enter things in different milliseconds, that's the expected behavior".

Not inserting it anywhere means that the test passes by "luck" (and it's a pattern for flaky tests waiting to happen in the future as things get faster).

The delay in the DAO wouldn't protect against ordering issues caused by concurrent access anyway, so to me that's a non-starter (and would give me shivers too!).

In any case, this millisecond approach is an interim hack until proper ordering arrives, so for that purpose it's certainly "good enough". I'd just really prefer if, as a principle, we avoided adding tests whose results depend on the speed of the machine running the test suite.

Comment (thibaultcha) [reply spec/02-integration/05-proxy/01-router_spec.lua]: Sold! I remembered this morning that we recently switched to using the same approach to reduce some flakiness related to the Targets ordering as well (https://github.com/Mashape/kong/pull/2849/files#diff-dce187085dbbafd3665dbc84cc63500dR294), so we should indeed stay consistent. 

> The delay in the DAO wouldn't protect against ordering issues caused by concurrent access anyway, so to me that's a non-starter (and would give me shivers too!).

Exactly, little we can do here about it, although generally users run scripts that send concurrent requests to the same node's Admin API. Luckily for us, our new model will have a better chance at dealing with this.
