### PR TITLE
fix(admin) fix regression of trailing slash in targets uri

### LINKED ISSUE #2840: Method Not Allowed when trying to fetch upstream's active targets
### Summary

When i want to fetch upstream's active targets i have a 400 response METHOD NOT ALLOWED

[https://getkong.org/docs/0.11.x/admin-api/#list-active-targets](https://getkong.org/docs/0.11.x/admin-api/#list-active-targets)

### Steps To Reproduce

1. `curl http://kong:8001/upstreams/{id}/targets/active -X GET`

### Additional Details & Logs

- Kong version (`0.11`)
- Operating System Linux
- If i add a `/` like this : `curl http://kong:8001/upstreams/{id}/targets/active/ -X GET` everything is ok, but not compliant with the documentation.
- An hotfix has been merged before in this pull request #2307
- The issue has been reintroduce by this pull request #2252

### PR DESCRIPTION
**Pull request by Tieske**
With the trailing slash the `.../targets/active` endpoint would return a "method not allowed" error

fixes #2840

### CODE REVIEW

File: kong/api/routes/upstreams.lua [hunk 1]
```diff
@@ -118,7 +118,7 @@ return {
     end,
   },
 
-  ["/upstreams/:upstream_name_or_id/targets/active/"] = {
```
Comment (thibaultcha) [inline kong/api/routes/upstreams.lua]: I believe (because I tested this yesterday) that removing this makes the endpoint works with both a trailing slash and without. We should also write a new regression test that ensures it is the case (after all, this is a regression we don't want to see happening again in the future).

Comment (Tieske) [reply kong/api/routes/upstreams.lua]: yep, good idea

File: spec/02-integration/04-admin_api/08-targets_routes_spec.lua [hunk 2]
```diff
@@ -302,24 +302,26 @@ describe("Admin API", function()
       end)
 
       it("only shows active targets", function()
-        local res = assert(client:send {
-          method = "GET",
-          path = "/upstreams/" .. upstream_name3 .. "/targets/active/",
-        })
-        assert.response(res).has.status(200)
-        local json = assert.response(res).has.jsonbody()
+        for _, append in ipairs({ "", "/" }) do
```
Comment (thibaultcha) [inline spec/02-integration/04-admin_api/08-targets_routes_spec.lua]: Not a blocker but fwiw, I don't think this is a healthy way of writing tests. If one behavior fails (with or without trailing slash), the developer sees a test named "only shows active targets" fail, which isn't what the test was actually asserting. On top of that, the developer has no easy way of knowing which of the two tests (the one with or without the trailing slash) failed, which is confusing and/or frustrating.

Tests must be atomic and explicit, always. "Meta-programming" testing (generating tests based on loops) should be avoided when it breaks the atomicity of the test.
