### PR TITLE
Fixing a bug when loading custom plugins

### LINKED ISSUE #1041: plugin enabled table merge error in version 0.7.0
Hi
I found a bug in kong 0.7.0 when I add some custom plugins to kong.yml.
when I use management api to get the plugins list  (http://localhost:8001/plugins/enabled)
I found the plugin names on the top of the list which should be the exist plugins are overwritten by the custom plugin names.

Perhaps it because the code below (kong/tools/config_loader.lua   row 185) 
config.plugins = utils.table_merge(constants.PLUGINS_AVAILABLE, config.custom_plugins)

When merge the two tables (key=index ,value=plugin name) with util.table_merge, the second table will  use the same index key to overwrite the first table's value but not append itself because they have the same key.

### PR DESCRIPTION
**Pull request by thefosk**
Closes #1041.

### CODE REVIEW

File: kong/tools/config_loader.lua [hunk 1]
```diff
@@ -182,7 +182,10 @@ function _M.load(config_path)
     config.nginx_working_dir = fs.current_dir().."/"..config.nginx_working_dir
   end
 
-  config.plugins = utils.table_merge(constants.PLUGINS_AVAILABLE, config.custom_plugins)
+  config.plugins = constants.PLUGINS_AVAILABLE
+  for _, v in ipairs(config.custom_plugins) do
+    table.insert(config.plugins, v)
+  end
```
Comment (Tieske) [inline kong/tools/config_loader.lua]: The original code had 3 tables; `config.plugins`, `constants.PLUGINS_AVAILABLE` and `config.custom_plugins`

The new code has only 2; `config.plugins` and `config.custom_plugins`, the one from `constants.PLUGINS_AVAILABLE` just points to the `config.plugins` one. So effectively you're copying the custom plugins into the constants table, which seems odd imo, why would it be a constant then?

Or is this intentional?

File: kong/tools/config_loader.lua [hunk 2]
```diff
@@ -182,7 +182,10 @@ function _M.load(config_path)
     config.nginx_working_dir = fs.current_dir().."/"..config.nginx_working_dir
   end
 
-  config.plugins = utils.table_merge(constants.PLUGINS_AVAILABLE, config.custom_plugins)
+  config.plugins = utils.deep_copy(constants.PLUGINS_AVAILABLE)
```
Comment (thefosk) [inline kong/tools/config_loader.lua]: @Tieske, your point was correct, this fixes the issue.
